---
- name: Install default Nginx web server
  hosts: debian

  tasks:
  - name: Install Nginx
    apt:
       name=nginx state=latest

  - name: Start Nginx and Enable
    service: name=nginx state=started enabled=yes
